---
language: python
python: "2.7"
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible #Install Ansible

script:
  - "ansible-playbook -i hosts server_setup.yml --syntax-check"
  - "ansible-playbook -i hosts server_setup.yml --connection=local --sudo"
  - >
    ansible-playbook -i hosts server_setup.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
