---
language: python
python: "2.7"
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y ansible #Install Ansible

script:
  - "ansible-playbook -i hosts --sudo test.yml --syntax-check"
  - "ansible-playbook -i hosts --sudo test.yml --connection=local"
  - >
    ansible-playbook -i hosts --sudo test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
