---
- hosts: localhost
  sudo: true
  vars:
    storage: /mnt/storage
  roles:
    - role: mergerfs
      mount_point: {{ storage }}
    - role: snapraid
      mount_point: {{ storage }}
    - role: docker
      mount_point: {{ storage }}
