- name: install samba
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - cifs-utils
    - samba
  notify:
    - start samba

- name: move samba config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify:
    - restart samba
