- name: download dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - g++
    - pkg-config
    - git-buildpackage
    - pandoc
    - debhelper
    - libfuse-dev
    - libattr1-dev

- name: clone mergerfs repo
  command: "git clone https://github.com/trapexit/mergerfs.git /tmp/mergerfs"

- name: make mergerfs
  command: "make --directory=/tmp/mergerfs deb"

- name: install mergerfs
  shell: "dpkg -i /tmp/mergerfs*.deb"

- name: remove mergerfs repo
  shell: "rm -rf /tmp/mergerfs*"
