- name: download dependancies
  apt:
    pkg: {{ item }}
    sudo: true
    state: present
    update_cache: yes
  with_items:
    - git
    - g++
    - pkg-config
    - git-buildpackage
    - pandoc
    - debhelper
    - libfuse-dev
    - libattr1-dev

- name: clone mergerfs repo
  git:
    repo: "git@github.com:trapexit/mergerfs.git"
    clone: yes
    dst: /tmp/mergerfs

- name: make mergerfs
  command: "make --directory=/tmp/mergerfs deb"

- name: install mergerfs
  command: "dpkg -i /tmp/mergerfs*.deb"

- name: remove mergerfs repo
  command: "rm -rf /tmp/mergerfs*"
