- name: check if mergerfs is installed
  command: which mergerfs
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- name: apt-get for mergerfs script
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - g++
    - pkg-config
    - git-buildpackage
    - pandoc
    - debhelper
    - libfuse-dev
    - libattr1-dev
  when: result | failed

- name: run mergerfs install script
  script: get_mergerfs.sh
  when: result | failed

- name: mount drives
  include: mount.yml #TODO test this
  when: disks.0 is defined
