- name: download dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - make
    - checkinstall

- name: download snapraid release
  get_url:
    dest: /tmp/snapraid.tar.gz
    force: yes
    url: "https://github.com/amadvance/snapraid/releases/download/v{{ snapraid_version }}/snapraid-{{ snapraid_version }}.tar.gz"

- name: untar snapraid release
  unarchive:
    src: /tmp/snapraid.tar.gz
    dest: /tmp

- name: configure snapraid
  command: "./configure"
  args:
    chdir: "/tmp/snapraid-{{ snapraid_version }}"

- name: make snapraid
  command: "make --directory=/tmp/snapraid-{{ snapraid_version }} check"

- name: install snapraid
  shell: "checkinstall -Dy --install=no --nodoc && dpkg -i *.deb"
  args:
    chdir: "/tmp/snapraid-{{ snapraid_version }}"

- name: remove snapraid files
  shell: "rm -rf /tmp/snapraid*"
