- name: check if snapraid is installed
  command: which snapraid
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- include: install.yml
  when: result | failed

- name: install and configure snapraid
  include: backup.yml
