- name: check if snapraid is installed
  command: which snapraid
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- name: snapraid apt-get
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - gcc
    - make
    - checkinstall

- include: install.yml
  when: result | failed

- name: install and configure snapraid
  include: backup.yml
