name: download dependancies
apt:
  pkg: {{ item }}
  sudo: true
  state: present
  update_cache: yes
with_items:
  - git
  - g++
  - pkg-config
  - git-buildpackage
  - pandoc
  - debhelper
  - libfuse-dev
  - libattr1-dev

name: clone mergerfs repo
git:
  repo: https://github.com/trapexit/mergerfs.git
  clone: yes
  dst: /tmp/mergerfs

name: install mergerfs
command: {{ item }}
with_items:
  - "make --directory=/tmp/mergerfs deb"
  - "dpkg -i /tmp/mergerfs*.deb"

name: remove mergerfs
command: "rm -rf /tmp/mergerfs*"
