- name: check if mergerfs is installed
  command: which mergerfs
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- include: install.yml
  when: result | failed

#TODO mount the drives to the single mount point
