- name: check if docker is installed
  command: which docker
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- name: run docker install script
  script: docker.sh
  when: result | failed

- name: install docker-py
  pip: name=docker-py state=present

- name: start docker daemon
  service: name=docker state=started

- name: make docker containers
  include: containers.yml
