- name: check if docker is installed
  command: which docker
  ignore_errors: True
  register: result
  changed_when: false
  always_run: yes

- name: install wget
  apt: name=wget state=present update_cache=yes

- name: run docker install script
  shell: "wget -qO- https://get.docker.com/ | sh"
  args:
    creates: /usr/bin/docker
  when: result | failed

- name: install docker-py
  pip: name=docker-py state=latest
  notify: restart docker

- name: add volume directories
  file:
    dest: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ volume }}"
    - "{{ movie }}"
    - "{{ tv }}"
    - "{{ download }}"
    - "{{ code }}"
    - "{{ cloud }}"

- name: make docker containers
  include: containers.yml
